(
	~places=Dictionary.with ( *[
			\patioL -> 6, \patioDoor -> 0,
			\brWall -> 1, \brDoor -> 2,
			\kitchL -> 3, \kitchR -> 4,
			\extL -> 5, \extR -> 6,
			\roof -> 7,
			\quad -> [0,1,2,5],
			\quadUp -> [1,2,5,6],
			\quadPairs -> [7,1,3,6],
			\pairs -> [1,3,5,6],		
		]
	);
)

//~places.at(\kitchL);
//~places[\kitchL];
//~places.keys;
//~places.findKeyForValue(6);

//Idea:
// play whole house tones
//crossfade with octal impulse
//or just quad

