~stills.set('Doctor?',14*60+36-0.25);
~stills.preview('Doctor?',text:[ "Doctor?","doctor" ])
~stills.set('same readings',14*60+41.3); 
~stills.preview('same readings',text:[ "I have the same readings","doctor" ])
~stills.set('hell die',14*60+45.0); 
~stills.preview('hell die',text:[ "he'll die","doctor" ])
~stills.set('what is it you want',14*60+48.0); 
~stills.set('in the next room',14*60+51.0); 
(
fork{
	~steals
}
)
