(
	Song(\theyUsed,[
		"they used to think if man could ","f3 f g g a a b ", //0
		"fly, he`d have wings, but he","b3 a g c#4 b c#", //1
		"did fly (boom boom)", "f", //2
		"(boom) he discovered he ","f",//3
		'had to.. do you wish that the first',"r r",//4
		'Apollo mission hadn`t reached the',"r r",//5
		'moon... or that we hadnt gone on to Mars ',"r r",//8"
		'and then to the nearest',"r r",//7"
		'star (boom boom) thats like saying you ',"r r",//9"
	])
)
