// default
" displayplacer \"id:1A8406AB-8D6E-73E1-E5D9-5BC83BA95E85 res:2560x1440 hz:60 color_depth:8 enabled:true scaling:off origin:(0,0) degree:0\" \"id:62C4AE15-912A-B886-22C4-75EC76BFB94B res:1440x900 color_depth:8 enabled:true scaling:on origin:(-1440,0) degree:0\" \"id:D1CCAD2F-3897-8E7D-A11F-24704BC1F22F res:1280x720 hz:60 color_depth:8 enabled:true scaling:off origin:(2560,0) degree:0\" ".unixCmd;

// macbook mirrored to projector 1, projector 2 
"displayplacer \"id:3EDE71FD-4E4-8D19-FE68-08AA3B9A74EF+62C4AE15-912A-B886-22C4-75EC76BFB94B res:1440x900 hz:60 color_depth:8 enabled:true scaling:on origin:(0,0) degree:0\" \"id:D1CCAD2F-3897-8E7D-A11F-24704BC1F22F res:1280x720 hz:60 color_depth:8 enabled:true scaling:off origin:(1440,-48) degree:0\"".unixCmd;

