//
//
// 
 __   ___ ___       __         ___  __    
|__) |__   |  |  | |__) |\ |    |  /  \   
|  \ |___  |  \__/ |  \ | \|    |  \__/   

___  __         __   __   __   __       
 |  /  \  |\/| /  \ |__) |__) /  \ |  | 
 |  \__/  |  | \__/ |  \ |  \ \__/ |/\| 
//
//
//
Trek.prepare
Song.cursor_(0);
(
fork{
	Stills.scale_(0.75);
	Trek.playRange(0, 0, 1); //section, cursor, numberOfSecs
	Trek.editFile(0);
}
)
s.pkill




