//
//
// 
 __   ___ ___       __         ___  __    
|__) |__   |  |  | |__) |\ |    |  /  \   
|  \ |___  |  \__/ |  \ | \|    |  \__/   

___  __         __   __   __   __       
 |  /  \  |\/| /  \ |__) |__) /  \ |  | 
 |  \__/  |  | \__/ |  \ |  \ \__/ |/\| 
//
//
//
Monitors.blackHole16 //check OBS sources
Trek.prepare
Stills.scale_(256/144)
Trek.recordOBS(numChannels: 5)
s.pkill
Trek.playAll



